import LeanSlang
import Cage

/-!
# `emit_cage` — cage.elf's kernels, their pins and binding table

Everything `kernels/cage/gen.sh` needs beyond `slangc` and the SPIR-V
embedding (`kernels/cage/embed_spv.cmake`), in Lean, so the kernel build
runs no Python (RFD 2239; the other stages' gen.sh call
`embed_spv.py` and `gen_avbd_kernel_table.py`):

    lake exe emit_cage slang <dir>             write <dir>/<k>.slang for every kernel
    lake exe emit_cage pin <lean/Cage/SlangCodegen>
                                               rewrite each module's `-- BEGIN PIN` block
                                               from the emission (then `lake build` checks it)
    lake exe emit_cage check-pins <dir>        exit 1 if a module's pin block is stale
    lake exe emit_cage table <out.inc>         the descriptor-binding table, from each
                                               shader's globals and numthreads
    lake exe emit_cage list                    the kernel names, one a line

The table is read from the Lean modules themselves rather than from
slangc's reflection JSON: the bindings are declared there, and the gen
script checks that each .spv validates (`spirv-val`).
-/

open LeanSlang
open Cage.Kernels

private def leanString (s : String) : String :=
  "\"" ++ (s.replace "\\" "\\\\" |>.replace "\"" "\\\"") ++ "\""

private def pinBlock (text : String) : String :=
  "-- BEGIN PIN\n" ++
  "def expected : String :=\n" ++ leanString text ++ "\n\n" ++
  "example : LeanSlang.emit shader = expected := by native_decide\n" ++
  "example : shader.entryPointName = \"main\" := by native_decide\n" ++
  "-- END PIN\n"

/-- Replace the `-- BEGIN PIN … -- END PIN` block of `src`. -/
private def repin (src block : String) : Option String :=
  match src.splitOn "-- BEGIN PIN\n" with
  | [pre, rest] =>
    match rest.splitOn "-- END PIN\n" with
    | [_, post] => some (pre ++ block ++ post)
    | _ => none
  | _ => none

private def descType : SlangType → Option (String × Bool)
  | .const _ => some ("VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER", true)
  | .roBuf _ => some ("VK_DESCRIPTOR_TYPE_STORAGE_BUFFER", true)
  | .rwBuf _ => some ("VK_DESCRIPTOR_TYPE_STORAGE_BUFFER", false)
  | _ => none

private def threads (m : SlangShaderModule) : Nat × Nat × Nat :=
  match m.entryPoint with
  | some f =>
    f.attrs.foldl (fun acc a => match a with | .numthreads x y z => (x, y, z) | _ => acc) (1, 1, 1)
  | none => (1, 1, 1)

private def table : String := Id.run do
  let mut out := "// GENERATED by `lake exe emit_cage table` (lean/EmitCage.lean) -- DO NOT EDIT.\n" ++
    "//\n// Descriptor bindings for each cage compute kernel, from the Lean modules'\n" ++
    "// globals. Regenerate with kernels/cage/gen.sh.\n\n" ++
    "#ifndef CLOTH_CAGE_KERNEL_TABLE_INC\n#define CLOTH_CAGE_KERNEL_TABLE_INC\n\n" ++
    "namespace cloth {\nnamespace cage_table {\n\n" ++
    "struct BindingDesc {\n\tconst char* name;\n\tuint32_t binding;\n\tVkDescriptorType type;\n\tbool readonly;\n};\n\n" ++
    "struct KernelDesc {\n\tconst char* name;          // basename; <name>.spv in the module dir\n" ++
    "\tconst char* entry;         // SPIR-V entry point\n\tuint32_t threadgroup[3];\n" ++
    "\tconst BindingDesc* bindings;\n\tuint32_t nBindings;\n" ++
    "\tint32_t paramsBinding;     // -1 when the kernel takes no params block\n};\n\n"
  let mut rows : List String := []
  for k in all do
    let bs := k.shader.globals.filterMap fun b =>
      match b.binding, descType b.type with
      | some i, some (ty, ro) => some (b.name, i, ty, ro)
      | _, _ => none
    out := out ++ s!"static const BindingDesc kBindings_{k.name}[] = \{\n"
    for (n, i, ty, ro) in bs do
      out := out ++ s!"\t\{ \"{n}\", {i}, {ty}, {if ro then "true" else "false"} },\n"
    out := out ++ "};\n\n"
    let pb := (bs.find? fun (_, _, ty, _) => ty == "VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER").map (fun (_, i, _, _) => (i : Int))
    let (x, y, z) := threads k.shader
    rows := rows ++ [s!"\t\{ \"{k.name}\", \"main\", \{ {x}, {y}, {z} }, kBindings_{k.name}, {bs.length}, {pb.getD (-1)} },\n"]
  out := out ++ "static const KernelDesc kKernels[] = {\n" ++ String.join rows ++ "};\n\n" ++
    "static const uint32_t kNumKernels = sizeof(kKernels) / sizeof(kKernels[0]);\n\n" ++
    "} // namespace cage_table\n} // namespace cloth\n\n#endif // CLOTH_CAGE_KERNEL_TABLE_INC\n"
  return out

def main (args : List String) : IO UInt32 := do
  match args with
  | ["slang", dir] =>
    IO.FS.createDirAll dir
    for k in all do
      IO.FS.writeFile (dir ++ "/" ++ k.name ++ ".slang") (LeanSlang.emit k.shader ++ "\n")
    IO.println s!"wrote {all.length} kernels to {dir}"
    return 0
  | ["pin", dir] | ["check-pins", dir] =>
    let check := args.head! == "check-pins"
    let mut stale : List String := []
    for k in all do
      let path := dir ++ "/" ++ k.module ++ ".lean"
      let src ← IO.FS.readFile path
      match repin src (pinBlock (LeanSlang.emit k.shader)) with
      | none => IO.eprintln s!"{path}: no PIN block"; return 2
      | some new =>
        if new != src then
          stale := stale ++ [k.module]
          if !check then IO.FS.writeFile path new
    if check then
      IO.println s!"stale pins: {if stale.isEmpty then "none" else String.intercalate ", " stale}"
      return (if stale.isEmpty then 0 else 1)
    IO.println s!"pinned {all.length} modules ({stale.length} changed)"
    return 0
  | ["table", out] =>
    IO.FS.writeFile out table
    IO.println s!"wrote {out}"
    return 0
  | ["list"] =>
    for k in all do IO.println k.name
    return 0
  | _ =>
    IO.eprintln "usage: emit_cage slang <dir> | pin <dir> | check-pins <dir> | table <out> | list"
    return 2
